export type Vendor = {
  slug: string;
  name: string;
  tagline: string;
  location: string;
  rating: number;
  reviewCount: number;
  joined: string;
  bio: string;
  accent: string;
  founder?: boolean;
};

export type Product = {
  slug: string;
  vendorSlug: string;
  title: string;
  category: string;
  price: number;
  priceType: "fixed" | "from" | "inquiry";
  blurb: string;
  bullets: string[];
  delivery: string;
  imageBg: string;
  imageEmoji: string;
  tags: string[];
};

export const categories = [
  "All",
  "Flips",
  "Whips",
  "Web & Tech",
  "Service",
  "Food",
  "Style",
  "Music",
  "Setup",
  "Fitness",
  "Consulting",
  "Custom",
];

export const vendors: Vendor[] = [
  {
    slug: "wzyotb",
    name: "wzyotb",
    tagline: "Founder · sells the keys",
    location: "California",
    rating: 5.0,
    reviewCount: 47,
    joined: "2026",
    bio: "Founder of WoozyKnows. I built this. I also build sites, do strategy calls, and plug people into my network. If you want in, talk to me first.",
    accent: "#0a0a0a",
    founder: true,
  },
  {
    slug: "big-bro-wholesale",
    name: "Big Bro Wholesale",
    tagline: "Bulk to flip",
    location: "Los Angeles, CA",
    rating: 4.7,
    reviewCount: 312,
    joined: "2023",
    bio: "We move bulk. Cables, electronics, household. You flip how you flip.",
    accent: "#1f1f1f",
  },
  {
    slug: "rico-rentals",
    name: "Rico Rentals",
    tagline: "Whips by the day",
    location: "Houston, TX",
    rating: 4.8,
    reviewCount: 187,
    joined: "2024",
    bio: "Daily, weekend, weekly. Sedans, SUVs, Chargers. Insured.",
    accent: "#c4361b",
  },
  {
    slug: "web-plug",
    name: "Web Plug",
    tagline: "Sites that move",
    location: "Remote",
    rating: 5.0,
    reviewCount: 64,
    joined: "2024",
    bio: "Landing pages. Full sites. Stores. No templates, no slow.",
    accent: "#2b4a8a",
  },
  {
    slug: "trap-detail",
    name: "Trap Detail",
    tagline: "Mobile detail",
    location: "Atlanta, GA",
    rating: 4.9,
    reviewCount: 421,
    joined: "2022",
    bio: "We pull up. Interior, exterior, ceramic. Fleets too.",
    accent: "#0e3b2e",
  },
  {
    slug: "cuts-by-quan",
    name: "Cuts by Quan",
    tagline: "House call barber",
    location: "Miami, FL",
    rating: 5.0,
    reviewCount: 256,
    joined: "2023",
    bio: "House calls. Weddings. Weekly tap-ins. Tue–Sat.",
    accent: "#7a1c1c",
  },
  {
    slug: "first-class-meals",
    name: "First Class Meals",
    tagline: "Plates done right",
    location: "Vacaville, CA",
    rating: 4.9,
    reviewCount: 98,
    joined: "2024",
    bio: "Weekly meal prep. Sunday platters. Private chef nights when you call.",
    accent: "#9c4a14",
  },
  {
    slug: "sneaker-plug",
    name: "Sneaker Plug",
    tagline: "Heat sourcing",
    location: "New York, NY",
    rating: 4.8,
    reviewCount: 540,
    joined: "2022",
    bio: "We find the pair. 1:1 search. Mystery boxes. Resell drops.",
    accent: "#000000",
  },
  {
    slug: "notary-now",
    name: "Notary Now",
    tagline: "Mobile notary, 24/7",
    location: "Bay Area, CA",
    rating: 5.0,
    reviewCount: 142,
    joined: "2023",
    bio: "Mobile signings, late nights, loan packets. Anywhere in the Bay.",
    accent: "#3b3b6e",
  },
  {
    slug: "quick-filings",
    name: "Quick Filings",
    tagline: "LLC, EIN, taxes",
    location: "Remote",
    rating: 4.8,
    reviewCount: 76,
    joined: "2024",
    bio: "Get your business legit. LLC, EIN, taxes — done in a week.",
    accent: "#1a4d3a",
  },
  {
    slug: "side-b-music",
    name: "Side B Music",
    tagline: "Beats, mix, master",
    location: "Atlanta, GA",
    rating: 4.9,
    reviewCount: 211,
    joined: "2023",
    bio: "Beats. Mix. Master. Indie + label. We cook.",
    accent: "#b8336a",
  },
  {
    slug: "studio-24",
    name: "Studio 24",
    tagline: "Music videos + content",
    location: "Memphis, TN",
    rating: 4.9,
    reviewCount: 89,
    joined: "2024",
    bio: "Music videos. Performance shoots. IG cuts. Same-week edits.",
    accent: "#3a2e6e",
  },
  {
    slug: "junk-out",
    name: "Junk Out",
    tagline: "Hauling + cleanouts",
    location: "Sacramento, CA",
    rating: 4.7,
    reviewCount: 168,
    joined: "2023",
    bio: "Truck. Crew. We clear it out. Same day.",
    accent: "#b08338",
  },
  {
    slug: "core-method",
    name: "Core Method",
    tagline: "Strength coaching",
    location: "Miami, FL",
    rating: 4.8,
    reviewCount: 124,
    joined: "2024",
    bio: "Programming + 1:1. Wynwood gym. Remote works too.",
    accent: "#d04a3a",
  },
  {
    slug: "ground-floor-advisory",
    name: "Ground Floor",
    tagline: "Founder coaching",
    location: "San Francisco, CA",
    rating: 4.9,
    reviewCount: 31,
    joined: "2024",
    bio: "Founder calls. Pricing. GTM. Fundraising prep. Pre-seed to seed.",
    accent: "#0f5c4a",
  },
];

export const products: Product[] = [
  // wzyotb — Founder
  {
    slug: "wzyotb-strategy-call",
    vendorSlug: "wzyotb",
    title: "Strategy call — 60 min",
    category: "Consulting",
    price: 300,
    priceType: "fixed",
    blurb: "One hour. You bring the problem. I bring the play.",
    bullets: ["60 min", "Pre-call brief", "Followup on Slack"],
    delivery: "Within 1 week",
    imageBg: "#0a0a0a",
    imageEmoji: "✦",
    tags: ["call", "strategy"],
  },
  {
    slug: "wzyotb-website-build",
    vendorSlug: "wzyotb",
    title: "Custom website build",
    category: "Web & Tech",
    price: 2500,
    priceType: "from",
    blurb: "Site like this one. Built for what you actually do, not a template.",
    bullets: ["Design + dev", "Ships in 2 weeks", "Vercel + analytics"],
    delivery: "2 weeks",
    imageBg: "#1a1a1a",
    imageEmoji: "▤",
    tags: ["site", "founder"],
  },
  {
    slug: "wzyotb-plug-me-in",
    vendorSlug: "wzyotb",
    title: "Plug me in",
    category: "Consulting",
    price: 0,
    priceType: "inquiry",
    blurb: "Tell me what you need. I make the intro. Network access, no markup.",
    bullets: ["Curated intros", "From my network", "Quote on the ask"],
    delivery: "Custom",
    imageBg: "#2a2a2a",
    imageEmoji: "→",
    tags: ["network", "intros"],
  },
  {
    slug: "wzyotb-quarterly-mentor",
    vendorSlug: "wzyotb",
    title: "Quarterly mentorship",
    category: "Consulting",
    price: 0,
    priceType: "inquiry",
    blurb: "I work with you for a quarter. Weekly calls, Slack on lock, real moves.",
    bullets: ["Weekly calls", "Slack always on", "Quote on scope"],
    delivery: "Custom",
    imageBg: "#3a3a3a",
    imageEmoji: "◆",
    tags: ["mentor", "founder"],
  },

  // Big Bro Wholesale — Flips
  {
    slug: "case-100-charger-cables",
    vendorSlug: "big-bro-wholesale",
    title: "100 charger cables",
    category: "Flips",
    price: 180,
    priceType: "fixed",
    blurb: "Hundred cables. Lightning + USB-C. Move how you move.",
    bullets: ["100 units", "Lightning + USB-C", "LA pickup or shipped"],
    delivery: "3 days",
    imageBg: "#1f1f1f",
    imageEmoji: "▤",
    tags: ["wholesale", "flip"],
  },
  {
    slug: "pallet-mixed-electronics",
    vendorSlug: "big-bro-wholesale",
    title: "Mixed electronics pallet",
    category: "Flips",
    price: 850,
    priceType: "from",
    blurb: "Returns + overstock. Phones, tablets, accessories. Manifest if you ask.",
    bullets: ["Manifest on request", "$2–4K MSRP", "LA pickup"],
    delivery: "1 week",
    imageBg: "#2c2c2c",
    imageEmoji: "▥",
    tags: ["pallet", "wholesale"],
  },
  {
    slug: "wholesale-custom-order",
    vendorSlug: "big-bro-wholesale",
    title: "Custom wholesale request",
    category: "Flips",
    price: 0,
    priceType: "inquiry",
    blurb: "Tell us what you flip. We source it. Quote in 24h.",
    bullets: ["Sourced for your niche", "Volume pricing", "24h quote"],
    delivery: "Custom",
    imageBg: "#3a3a3a",
    imageEmoji: "?",
    tags: ["custom", "sourcing"],
  },

  // Rico Rentals — Whips
  {
    slug: "daily-rental-charger",
    vendorSlug: "rico-rentals",
    title: "Charger — daily",
    category: "Whips",
    price: 95,
    priceType: "fixed",
    blurb: "Charger. Tank's full. 200 miles is yours. Insured.",
    bullets: ["24 hours", "200 mi", "Insurance included"],
    delivery: "Same day",
    imageBg: "#c4361b",
    imageEmoji: "✦",
    tags: ["rental", "daily"],
  },
  {
    slug: "weekend-suv",
    vendorSlug: "rico-rentals",
    title: "SUV — weekend",
    category: "Whips",
    price: 480,
    priceType: "fixed",
    blurb: "Tahoe or Suburban. Friday to Sunday. Unlimited miles.",
    bullets: ["3 days", "Unlimited miles", "Family-trip ready"],
    delivery: "Friday",
    imageBg: "#7a1c10",
    imageEmoji: "■",
    tags: ["weekend", "suv"],
  },
  {
    slug: "long-trip-custom",
    vendorSlug: "rico-rentals",
    title: "Long trip / custom dates",
    category: "Whips",
    price: 0,
    priceType: "inquiry",
    blurb: "Out of town a week+? Send dates, we quote.",
    bullets: ["Weekly + monthly", "Custom mileage", "Out-of-state OK"],
    delivery: "Custom",
    imageBg: "#9c2616",
    imageEmoji: "→",
    tags: ["custom", "long-trip"],
  },

  // Web Plug — Web & Tech
  {
    slug: "landing-page-plug",
    vendorSlug: "web-plug",
    title: "Landing page",
    category: "Web & Tech",
    price: 500,
    priceType: "fixed",
    blurb: "One page. Live in 5 days. Converts or we redo it.",
    bullets: ["Design + dev", "Mobile + desktop", "Vercel deploy"],
    delivery: "5 days",
    imageBg: "#2b4a8a",
    imageEmoji: "▦",
    tags: ["site", "fast"],
  },
  {
    slug: "full-site-plug",
    vendorSlug: "web-plug",
    title: "Full site (5 pages)",
    category: "Web & Tech",
    price: 1500,
    priceType: "fixed",
    blurb: "Home, services, about, gallery, contact. Two weeks, you're up.",
    bullets: ["5 pages", "CMS optional", "Ships in 2 weeks"],
    delivery: "2 weeks",
    imageBg: "#3a5fa8",
    imageEmoji: "▣",
    tags: ["site", "full"],
  },
  {
    slug: "ecommerce-plug",
    vendorSlug: "web-plug",
    title: "Online store",
    category: "Web & Tech",
    price: 2500,
    priceType: "from",
    blurb: "Stripe, inventory, the whole bag. Quote scales with your catalog.",
    bullets: ["Stripe checkout", "Up to 50 SKUs", "Admin panel"],
    delivery: "3 weeks",
    imageBg: "#5878c4",
    imageEmoji: "$",
    tags: ["ecommerce", "stripe"],
  },

  // Trap Detail — Service
  {
    slug: "detail-sedan",
    vendorSlug: "trap-detail",
    title: "Detail — sedan",
    category: "Service",
    price: 80,
    priceType: "fixed",
    blurb: "We pull up. Wash, vac, wipe down, tires shining.",
    bullets: ["Interior + exterior", "Mobile", "~90 min"],
    delivery: "Same week",
    imageBg: "#0e3b2e",
    imageEmoji: "●",
    tags: ["detail", "mobile"],
  },
  {
    slug: "detail-suv-truck",
    vendorSlug: "trap-detail",
    title: "Detail — SUV / truck",
    category: "Service",
    price: 140,
    priceType: "fixed",
    blurb: "Bigger ride, deeper clean. Steam everything.",
    bullets: ["Steam clean", "~2 hours", "Mobile"],
    delivery: "Same week",
    imageBg: "#1a5240",
    imageEmoji: "◆",
    tags: ["detail", "suv"],
  },
  {
    slug: "ceramic-coating",
    vendorSlug: "trap-detail",
    title: "Ceramic coating",
    category: "Service",
    price: 0,
    priceType: "inquiry",
    blurb: "2-year ceramic, paint correction, the works. Quote on the ride.",
    bullets: ["Paint correction", "2-yr ceramic", "Quote per car"],
    delivery: "Custom",
    imageBg: "#266a52",
    imageEmoji: "◯",
    tags: ["ceramic", "premium"],
  },

  // Cuts by Quan — Style
  {
    slug: "house-call-cut",
    vendorSlug: "cuts-by-quan",
    title: "House call cut",
    category: "Style",
    price: 60,
    priceType: "fixed",
    blurb: "We pull up. Cut + lineup. Tip optional but appreciated.",
    bullets: ["Cut + lineup", "At your spot", "~30 min"],
    delivery: "Within 48h",
    imageBg: "#7a1c1c",
    imageEmoji: "✂",
    tags: ["barber", "house-call"],
  },
  {
    slug: "cut-beard-package",
    vendorSlug: "cuts-by-quan",
    title: "Cut + lineup + beard",
    category: "Style",
    price: 80,
    priceType: "fixed",
    blurb: "Full reset. Cut, lineup, beard, hot towel.",
    bullets: ["Cut + lineup", "Beard shape", "Hot towel"],
    delivery: "Within 48h",
    imageBg: "#a02929",
    imageEmoji: "▲",
    tags: ["barber", "beard"],
  },
  {
    slug: "wedding-event",
    vendorSlug: "cuts-by-quan",
    title: "Wedding / event",
    category: "Style",
    price: 200,
    priceType: "from",
    blurb: "Groom + groomsmen on-site. Group rate, locked in.",
    bullets: ["Up to 6 heads", "On-site", "Group rate"],
    delivery: "Per booking",
    imageBg: "#d04a3a",
    imageEmoji: "♛",
    tags: ["wedding", "event"],
  },

  // First Class Meals — Food
  {
    slug: "meal-prep-week",
    vendorSlug: "first-class-meals",
    title: "Meal prep — week of 10",
    category: "Food",
    price: 120,
    priceType: "fixed",
    blurb: "10 plates. Macros on point. Sunday delivery, all week ready.",
    bullets: ["10 meals", "Sunday delivery", "Macros on the lid"],
    delivery: "Sundays",
    imageBg: "#9c4a14",
    imageEmoji: "▭",
    tags: ["meal-prep", "weekly"],
  },
  {
    slug: "sunday-platter",
    vendorSlug: "first-class-meals",
    title: "Sunday dinner platter",
    category: "Food",
    price: 85,
    priceType: "fixed",
    blurb: "Family-style. Feeds 4–6. Sunday only.",
    bullets: ["Feeds 4–6", "Sunday only", "Pickup or local delivery"],
    delivery: "Sundays",
    imageBg: "#c4631c",
    imageEmoji: "❀",
    tags: ["sunday", "family"],
  },
  {
    slug: "private-chef-night",
    vendorSlug: "first-class-meals",
    title: "Private chef night",
    category: "Food",
    price: 0,
    priceType: "inquiry",
    blurb: "We come cook at your spot. Birthdays, dates, family.",
    bullets: ["Cooked on-site", "Custom menu", "Quote on guest count"],
    delivery: "Custom",
    imageBg: "#d4823a",
    imageEmoji: "⚐",
    tags: ["private-chef", "custom"],
  },

  // Sneaker Plug — Style
  {
    slug: "mystery-sneaker-box",
    vendorSlug: "sneaker-plug",
    title: "Mystery sneaker box",
    category: "Style",
    price: 150,
    priceType: "fixed",
    blurb: "One pair. You don't know what. Authenticated, $200–500 resale.",
    bullets: ["1 mystery pair", "Authenticated", "Resale guide"],
    delivery: "1 week",
    imageBg: "#000000",
    imageEmoji: "◯",
    tags: ["sneakers", "mystery"],
  },
  {
    slug: "sneaker-1to1-search",
    vendorSlug: "sneaker-plug",
    title: "1:1 sneaker search",
    category: "Style",
    price: 0,
    priceType: "inquiry",
    blurb: "Pair + size. We hunt. Quote w/ markup.",
    bullets: ["Any model + size", "Markup quoted", "Authenticated"],
    delivery: "Custom",
    imageBg: "#1a1a1a",
    imageEmoji: "✓",
    tags: ["custom", "search"],
  },
  {
    slug: "fit-drop-bulk",
    vendorSlug: "sneaker-plug",
    title: "Bulk fit drop (10 items)",
    category: "Style",
    price: 400,
    priceType: "from",
    blurb: "10 mixed pieces — tees, hoodies, accessories. Resell-ready.",
    bullets: ["10 items", "Resell-ready", "Mixed sizes"],
    delivery: "1 week",
    imageBg: "#2c2c2c",
    imageEmoji: "▦",
    tags: ["clothing", "bulk"],
  },

  // Notary Now — Service
  {
    slug: "single-notarization",
    vendorSlug: "notary-now",
    title: "Single signing — mobile",
    category: "Service",
    price: 35,
    priceType: "fixed",
    blurb: "One doc, anywhere in the Bay, day or night.",
    bullets: ["1 document", "Mobile", "24/7"],
    delivery: "Same day",
    imageBg: "#3b3b6e",
    imageEmoji: "✎",
    tags: ["notary", "mobile"],
  },
  {
    slug: "loan-signing-package",
    vendorSlug: "notary-now",
    title: "Loan signing — full packet",
    category: "Service",
    price: 150,
    priceType: "fixed",
    blurb: "Full loan packet, signed mobile, shipped same day.",
    bullets: ["Full packet", "Mobile", "Shipped same day"],
    delivery: "Same day",
    imageBg: "#5151a8",
    imageEmoji: "▤",
    tags: ["loan", "signing"],
  },

  // Quick Filings — Setup
  {
    slug: "llc-formation-ein",
    vendorSlug: "quick-filings",
    title: "LLC + EIN",
    category: "Setup",
    price: 250,
    priceType: "fixed",
    blurb: "LLC filed. EIN issued. Operating agreement in your inbox. State fees on you.",
    bullets: ["LLC filing", "EIN", "Operating agreement"],
    delivery: "1 week",
    imageBg: "#1a4d3a",
    imageEmoji: "▣",
    tags: ["llc", "setup"],
  },
  {
    slug: "tax-prep-single",
    vendorSlug: "quick-filings",
    title: "Tax prep — single filer",
    category: "Setup",
    price: 150,
    priceType: "fixed",
    blurb: "Federal + one state. W-2 + basic 1099. E-filed, done.",
    bullets: ["Federal + state", "W-2 + 1099", "E-filed"],
    delivery: "3 days",
    imageBg: "#2a6e54",
    imageEmoji: "$",
    tags: ["tax", "filing"],
  },
  {
    slug: "business-setup-full",
    vendorSlug: "quick-filings",
    title: "Full business setup",
    category: "Setup",
    price: 750,
    priceType: "from",
    blurb: "LLC, EIN, business bank, books, first year filing. You're legit.",
    bullets: ["LLC + EIN", "Bank guidance", "Books starter kit"],
    delivery: "2 weeks",
    imageBg: "#3a8a6a",
    imageEmoji: "◆",
    tags: ["setup", "package"],
  },

  // Side B Music — Music
  {
    slug: "custom-beat",
    vendorSlug: "side-b-music",
    title: "Custom beat",
    category: "Music",
    price: 450,
    priceType: "fixed",
    blurb: "Original. Your direction. Exclusive license, stems on the way out.",
    bullets: ["Exclusive", "Stems delivered", "2 revisions"],
    delivery: "10 days",
    imageBg: "#b8336a",
    imageEmoji: "♪",
    tags: ["beat", "exclusive"],
  },
  {
    slug: "mix-master-single",
    vendorSlug: "side-b-music",
    title: "Mix + master single",
    category: "Music",
    price: 350,
    priceType: "fixed",
    blurb: "Up to 24 stems. Mix, master, WAV + MP3 back to you.",
    bullets: ["Up to 24 stems", "1 revision", "WAV + MP3"],
    delivery: "5 days",
    imageBg: "#d04685",
    imageEmoji: "≈",
    tags: ["mix", "master"],
  },
  {
    slug: "ad-music-license",
    vendorSlug: "side-b-music",
    title: "Custom ad / sync music",
    category: "Music",
    price: 0,
    priceType: "inquiry",
    blurb: "Music for ads, films, brand spots. Sync rights cleared. Quote on use.",
    bullets: ["Custom comp", "Sync rights", "Quote on use"],
    delivery: "Custom",
    imageBg: "#9c2854",
    imageEmoji: "♫",
    tags: ["sync", "ads"],
  },

  // Studio 24 — Music
  {
    slug: "music-video-single",
    vendorSlug: "studio-24",
    title: "Music video — single song",
    category: "Music",
    price: 400,
    priceType: "fixed",
    blurb: "One song. One spot. One outfit. Edit in your inbox in 7.",
    bullets: ["1 location", "1 outfit", "Edit in 7 days"],
    delivery: "1 week",
    imageBg: "#3a2e6e",
    imageEmoji: "▶",
    tags: ["music-video", "shoot"],
  },
  {
    slug: "performance-shoot",
    vendorSlug: "studio-24",
    title: "Performance shoot — 4 hours",
    category: "Music",
    price: 250,
    priceType: "fixed",
    blurb: "Live performance, multi-cam, in-studio. IG cuts come with it.",
    bullets: ["4 hours", "Multi-cam", "IG cuts included"],
    delivery: "5 days",
    imageBg: "#5a47a8",
    imageEmoji: "◐",
    tags: ["performance", "video"],
  },
  {
    slug: "tour-content-package",
    vendorSlug: "studio-24",
    title: "Tour content package",
    category: "Music",
    price: 0,
    priceType: "inquiry",
    blurb: "We travel with you. Every show, every city. Daily IG drops.",
    bullets: ["Travels with you", "Daily IG cuts", "Quote on length"],
    delivery: "Custom",
    imageBg: "#7a64c4",
    imageEmoji: "✦",
    tags: ["tour", "custom"],
  },

  // Junk Out — Service
  {
    slug: "single-item-haul",
    vendorSlug: "junk-out",
    title: "Single item haul",
    category: "Service",
    price: 80,
    priceType: "fixed",
    blurb: "Old couch, broken fridge, that thing in the garage — gone.",
    bullets: ["1 item", "Same day", "Truck + crew"],
    delivery: "Same day",
    imageBg: "#b08338",
    imageEmoji: "▼",
    tags: ["haul", "single"],
  },
  {
    slug: "apartment-cleanout",
    vendorSlug: "junk-out",
    title: "Apartment cleanout",
    category: "Service",
    price: 350,
    priceType: "from",
    blurb: "Whole unit cleared. Studio to 2BR. Donate-able stuff goes to a home.",
    bullets: ["Full unit", "Same day", "Donations included"],
    delivery: "Same week",
    imageBg: "#c99848",
    imageEmoji: "◫",
    tags: ["cleanout", "apartment"],
  },
  {
    slug: "estate-cleanout",
    vendorSlug: "junk-out",
    title: "Estate cleanout",
    category: "Service",
    price: 0,
    priceType: "inquiry",
    blurb: "Full house. Sensitive situations. We move quiet.",
    bullets: ["Full house", "Discreet crew", "Quote on volume"],
    delivery: "Custom",
    imageBg: "#d4a558",
    imageEmoji: "◇",
    tags: ["estate", "custom"],
  },

  // Core Method — Fitness
  {
    slug: "in-person-session",
    vendorSlug: "core-method",
    title: "In-person session — Miami",
    category: "Fitness",
    price: 140,
    priceType: "fixed",
    blurb: "1:1 in the Wynwood gym. Hour. You leave smoked.",
    bullets: ["60 min", "1:1", "Wynwood"],
    delivery: "Book within 7 days",
    imageBg: "#d04a3a",
    imageEmoji: "●",
    tags: ["1:1", "miami"],
  },
  {
    slug: "remote-programming-monthly",
    vendorSlug: "core-method",
    title: "Remote programming — monthly",
    category: "Fitness",
    price: 250,
    priceType: "fixed",
    blurb: "Custom program. Updated weekly. Slack check-ins, no excuses.",
    bullets: ["Updated weekly", "App-based", "Slack access"],
    delivery: "Monthly",
    imageBg: "#f25040",
    imageEmoji: "▲",
    tags: ["programming", "remote"],
  },
  {
    slug: "form-check-video",
    vendorSlug: "core-method",
    title: "Form check video review",
    category: "Fitness",
    price: 60,
    priceType: "fixed",
    blurb: "Send a clip. Get a video breakdown back in 48.",
    bullets: ["Async", "Video breakdown", "48h turnaround"],
    delivery: "48 hours",
    imageBg: "#f8e3df",
    imageEmoji: "▷",
    tags: ["form", "async"],
  },

  // Ground Floor — Consulting
  {
    slug: "founder-coaching-session",
    vendorSlug: "ground-floor-advisory",
    title: "90-min founder session",
    category: "Consulting",
    price: 500,
    priceType: "fixed",
    blurb: "One deep call. Pricing, GTM, or fundraising. Written followup after.",
    bullets: ["90 min", "Pre-call prep", "Written followup"],
    delivery: "Within 1 week",
    imageBg: "#0f5c4a",
    imageEmoji: "◆",
    tags: ["coaching", "session"],
  },
  {
    slug: "fundraising-prep",
    vendorSlug: "ground-floor-advisory",
    title: "Pre-seed fundraising prep",
    category: "Consulting",
    price: 4500,
    priceType: "from",
    blurb: "Deck, narrative, target list, four prep sessions. You walk in ready.",
    bullets: ["Deck review", "Pitch coaching", "Investor list"],
    delivery: "3 weeks",
    imageBg: "#1a7a62",
    imageEmoji: "▣",
    tags: ["fundraising", "deck"],
  },
  {
    slug: "advisory-quarterly",
    vendorSlug: "ground-floor-advisory",
    title: "Quarterly advisory",
    category: "Consulting",
    price: 0,
    priceType: "inquiry",
    blurb: "Embedded advisor for one quarter. Equity or cash. Weekly calls, Slack always on.",
    bullets: ["Weekly calls", "Slack access", "Quote on scope"],
    delivery: "Custom",
    imageBg: "#2a9c7a",
    imageEmoji: "✦",
    tags: ["advisor", "custom"],
  },
];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getVendor(slug: string): Vendor | undefined {
  return vendors.find((v) => v.slug === slug);
}

export function productsByVendor(vendorSlug: string): Product[] {
  return products.filter((p) => p.vendorSlug === vendorSlug);
}

export function formatPrice(p: Product): string {
  if (p.priceType === "inquiry") return "Inquire";
  const formatted = `$${p.price.toLocaleString()}`;
  return p.priceType === "from" ? `From ${formatted}` : formatted;
}
