export type Vendor = {
  slug: string;
  name: string;
  tagline: string;
  location: string;
  rating: number;
  reviewCount: number;
  joined: string;
  bio: string;
  accent: string;
};

export type Product = {
  slug: string;
  vendorSlug: string;
  title: string;
  category: string;
  price: number;
  priceType: "fixed" | "from" | "inquiry";
  blurb: string;
  bullets: string[];
  delivery: string;
  imageBg: string;
  imageEmoji: string;
  tags: string[];
};

export const categories = [
  "All",
  "Branding",
  "Web & App",
  "Photo & Video",
  "Marketing",
  "Music",
  "Tutoring",
  "Fitness",
  "Writing",
  "Consulting",
  "Custom",
];

export const vendors: Vendor[] = [
  {
    slug: "atelier-noma",
    name: "Atelier Noma",
    tagline: "Brand identity studio",
    location: "Brooklyn, NY",
    rating: 4.9,
    reviewCount: 142,
    joined: "2024",
    bio: "Identity systems for restaurants, hotels, and product brands. Two-person studio. Booking 6 weeks out.",
    accent: "#1a1a1a",
  },
  {
    slug: "kit-and-co",
    name: "Kit & Co.",
    tagline: "Web build studio",
    location: "Austin, TX",
    rating: 4.8,
    reviewCount: 89,
    joined: "2024",
    bio: "Marketing sites and landing pages for early-stage companies. Ship in 2 weeks or less.",
    accent: "#7a5cff",
  },
  {
    slug: "north-light",
    name: "North Light",
    tagline: "Photo & video",
    location: "Los Angeles, CA",
    rating: 5.0,
    reviewCount: 67,
    joined: "2025",
    bio: "Editorial product photography and short-form brand films. Studio + on-location.",
    accent: "#c98a3b",
  },
  {
    slug: "field-notes-marketing",
    name: "Field Notes",
    tagline: "Growth marketing",
    location: "Remote",
    rating: 4.7,
    reviewCount: 211,
    joined: "2023",
    bio: "Performance marketing for DTC brands. Meta, TikTok, paid search.",
    accent: "#2c6e49",
  },
  {
    slug: "side-b-music",
    name: "Side B Music",
    tagline: "Production & mixing",
    location: "Atlanta, GA",
    rating: 4.9,
    reviewCount: 54,
    joined: "2024",
    bio: "Beats, mixing, mastering. Worked with indie artists and ad agencies.",
    accent: "#b8336a",
  },
  {
    slug: "mara-tutoring",
    name: "Mara",
    tagline: "Test prep tutor",
    location: "Remote",
    rating: 5.0,
    reviewCount: 38,
    joined: "2025",
    bio: "SAT and college-level math. Former MIT TA. 1:1 only.",
    accent: "#3a5a8c",
  },
  {
    slug: "core-method",
    name: "Core Method",
    tagline: "Strength coaching",
    location: "Miami, FL",
    rating: 4.8,
    reviewCount: 124,
    joined: "2024",
    bio: "Programming and remote coaching for lifters. Plus in-person sessions in Miami.",
    accent: "#d04a3a",
  },
  {
    slug: "longform-co",
    name: "Longform Co.",
    tagline: "Writing & editing",
    location: "Remote",
    rating: 4.9,
    reviewCount: 76,
    joined: "2023",
    bio: "Essays, newsletters, ghostwriting for founders.",
    accent: "#4a4a4a",
  },
  {
    slug: "ground-floor-advisory",
    name: "Ground Floor",
    tagline: "Founder consulting",
    location: "San Francisco, CA",
    rating: 4.9,
    reviewCount: 31,
    joined: "2024",
    bio: "Pre-seed and seed founder coaching. Pricing, GTM, fundraising prep.",
    accent: "#0f5c4a",
  },
  {
    slug: "studio-paloma",
    name: "Studio Paloma",
    tagline: "Interior styling",
    location: "Mexico City, MX",
    rating: 5.0,
    reviewCount: 22,
    joined: "2025",
    bio: "Interior styling and shoot direction. Hospitality and residential.",
    accent: "#9c6644",
  },
];

export const products: Product[] = [
  // Atelier Noma
  {
    slug: "logo-mark-only",
    vendorSlug: "atelier-noma",
    title: "Logo mark only",
    category: "Branding",
    price: 1200,
    priceType: "fixed",
    blurb: "A single mark, three rounds, final files in vector + raster.",
    bullets: ["3 concepts", "2 rounds of revisions", "SVG, PNG, PDF delivery"],
    delivery: "10 days",
    imageBg: "#1a1a1a",
    imageEmoji: "✦",
    tags: ["logo", "identity"],
  },
  {
    slug: "full-identity-system",
    vendorSlug: "atelier-noma",
    title: "Full identity system",
    category: "Branding",
    price: 8500,
    priceType: "from",
    blurb: "Logo, type, color, brand book, and basic launch assets.",
    bullets: ["Logo + variations", "Typography + color", "Brand guidelines PDF"],
    delivery: "4–6 weeks",
    imageBg: "#f3efe6",
    imageEmoji: "◐",
    tags: ["identity", "system", "premium"],
  },
  {
    slug: "menu-design",
    vendorSlug: "atelier-noma",
    title: "Restaurant menu design",
    category: "Branding",
    price: 650,
    priceType: "fixed",
    blurb: "Print-ready menu layout, your copy and brand assets.",
    bullets: ["1 menu design", "Print + digital files", "1 round of edits"],
    delivery: "5 days",
    imageBg: "#e8e2d4",
    imageEmoji: "❘❘❘",
    tags: ["print", "restaurant"],
  },

  // Kit & Co.
  {
    slug: "landing-page-build",
    vendorSlug: "kit-and-co",
    title: "Landing page build",
    category: "Web & App",
    price: 2500,
    priceType: "fixed",
    blurb: "Single-page site with copy, design, and dev. Live in 7 days.",
    bullets: ["Design + dev", "Copy support", "Vercel deploy"],
    delivery: "7 days",
    imageBg: "#7a5cff",
    imageEmoji: "▤",
    tags: ["site", "fast"],
  },
  {
    slug: "marketing-site-5pg",
    vendorSlug: "kit-and-co",
    title: "5-page marketing site",
    category: "Web & App",
    price: 6500,
    priceType: "from",
    blurb: "Home, product, pricing, about, contact. Built on Next.js.",
    bullets: ["Up to 5 pages", "CMS optional", "2 weeks to ship"],
    delivery: "2 weeks",
    imageBg: "#efeafe",
    imageEmoji: "▦",
    tags: ["site", "next.js"],
  },
  {
    slug: "webflow-to-next-migration",
    vendorSlug: "kit-and-co",
    title: "Webflow → Next.js migration",
    category: "Web & App",
    price: 0,
    priceType: "inquiry",
    blurb: "Move your Webflow site to a custom Next.js codebase.",
    bullets: ["Pixel match", "SEO preserved", "Quote based on scope"],
    delivery: "Custom",
    imageBg: "#d8ccff",
    imageEmoji: "↻",
    tags: ["migration", "custom"],
  },

  // North Light
  {
    slug: "product-shoot-day",
    vendorSlug: "north-light",
    title: "Product shoot — half day",
    category: "Photo & Video",
    price: 1800,
    priceType: "fixed",
    blurb: "Studio half day. Up to 12 final retouched product shots.",
    bullets: ["4 hours studio", "12 retouched", "Lifestyle + flat"],
    delivery: "5 days",
    imageBg: "#c98a3b",
    imageEmoji: "◯",
    tags: ["product", "studio"],
  },
  {
    slug: "brand-film-30s",
    vendorSlug: "north-light",
    title: "30s brand film",
    category: "Photo & Video",
    price: 7500,
    priceType: "from",
    blurb: "Director, crew, edit. Cut for paid social and your homepage.",
    bullets: ["1 shoot day", "30s + 15s + 6s cuts", "Color + sound"],
    delivery: "3 weeks",
    imageBg: "#f5e6d0",
    imageEmoji: "▶",
    tags: ["video", "ads"],
  },
  {
    slug: "headshots-team",
    vendorSlug: "north-light",
    title: "Team headshots (10 people)",
    category: "Photo & Video",
    price: 1400,
    priceType: "fixed",
    blurb: "On-site or studio. 2 looks per person, retouched.",
    bullets: ["10 people", "2 final per person", "On-site option"],
    delivery: "1 week",
    imageBg: "#eddcc4",
    imageEmoji: "☉",
    tags: ["headshots", "team"],
  },

  // Field Notes Marketing
  {
    slug: "meta-ads-audit",
    vendorSlug: "field-notes-marketing",
    title: "Meta ads audit",
    category: "Marketing",
    price: 350,
    priceType: "fixed",
    blurb: "60-min audit + written report on your account.",
    bullets: ["Account audit", "Written report", "30-day plan"],
    delivery: "3 days",
    imageBg: "#2c6e49",
    imageEmoji: "≣",
    tags: ["audit", "ads"],
  },
  {
    slug: "ads-management-monthly",
    vendorSlug: "field-notes-marketing",
    title: "Ads management — monthly",
    category: "Marketing",
    price: 2400,
    priceType: "from",
    blurb: "Hands-on Meta + TikTok management. Monthly retainer.",
    bullets: ["Meta + TikTok", "Weekly creative", "Reporting"],
    delivery: "Monthly",
    imageBg: "#dceede",
    imageEmoji: "↗",
    tags: ["retainer", "ads"],
  },
  {
    slug: "creative-strategy-call",
    vendorSlug: "field-notes-marketing",
    title: "Creative strategy call",
    category: "Marketing",
    price: 200,
    priceType: "fixed",
    blurb: "60-min call. Fresh angles for your ad creative.",
    bullets: ["60 min", "Recording", "Action list"],
    delivery: "Same week",
    imageBg: "#c9e4cf",
    imageEmoji: "✎",
    tags: ["call", "creative"],
  },

  // Side B Music
  {
    slug: "custom-beat",
    vendorSlug: "side-b-music",
    title: "Custom beat",
    category: "Music",
    price: 450,
    priceType: "fixed",
    blurb: "Original beat, your direction, exclusive license.",
    bullets: ["Exclusive", "Stems delivered", "2 revisions"],
    delivery: "10 days",
    imageBg: "#b8336a",
    imageEmoji: "♪",
    tags: ["beat", "music"],
  },
  {
    slug: "mix-and-master",
    vendorSlug: "side-b-music",
    title: "Mix + master single",
    category: "Music",
    price: 350,
    priceType: "fixed",
    blurb: "Up to 24 stems. Mix and master one track.",
    bullets: ["Up to 24 stems", "1 revision", "WAV + MP3"],
    delivery: "5 days",
    imageBg: "#f0d6e0",
    imageEmoji: "≈",
    tags: ["mix", "master"],
  },
  {
    slug: "ad-music-license",
    vendorSlug: "side-b-music",
    title: "Custom ad music",
    category: "Music",
    price: 0,
    priceType: "inquiry",
    blurb: "Music for ads, films, brand spots. Quote on scope.",
    bullets: ["Custom composition", "Sync rights", "Quote based on use"],
    delivery: "Custom",
    imageBg: "#e8c8d4",
    imageEmoji: "♫",
    tags: ["ads", "sync"],
  },

  // Mara Tutoring
  {
    slug: "sat-math-package",
    vendorSlug: "mara-tutoring",
    title: "SAT math — 8 sessions",
    category: "Tutoring",
    price: 880,
    priceType: "fixed",
    blurb: "Eight 60-min sessions over 4 weeks. 1:1.",
    bullets: ["8 sessions", "1:1 only", "Weekly homework"],
    delivery: "4 weeks",
    imageBg: "#3a5a8c",
    imageEmoji: "∑",
    tags: ["sat", "math"],
  },
  {
    slug: "single-session",
    vendorSlug: "mara-tutoring",
    title: "Single tutoring session",
    category: "Tutoring",
    price: 120,
    priceType: "fixed",
    blurb: "One 60-min session. Try before you commit.",
    bullets: ["60 minutes", "Any topic", "Recording included"],
    delivery: "Within 1 week",
    imageBg: "#d6dfee",
    imageEmoji: "✚",
    tags: ["session"],
  },

  // Core Method
  {
    slug: "remote-programming-monthly",
    vendorSlug: "core-method",
    title: "Remote programming — monthly",
    category: "Fitness",
    price: 250,
    priceType: "fixed",
    blurb: "Custom training program updated weekly.",
    bullets: ["Updated weekly", "App-based", "Slack check-ins"],
    delivery: "Monthly",
    imageBg: "#d04a3a",
    imageEmoji: "▲",
    tags: ["programming", "remote"],
  },
  {
    slug: "in-person-session",
    vendorSlug: "core-method",
    title: "In-person session — Miami",
    category: "Fitness",
    price: 140,
    priceType: "fixed",
    blurb: "1:1 session at our Wynwood gym.",
    bullets: ["60 min", "1:1", "Wynwood location"],
    delivery: "Book within 7 days",
    imageBg: "#f4d4cf",
    imageEmoji: "●",
    tags: ["1:1", "miami"],
  },
  {
    slug: "form-check-video",
    vendorSlug: "core-method",
    title: "Form check video review",
    category: "Fitness",
    price: 60,
    priceType: "fixed",
    blurb: "Send a clip. Get a video breakdown back in 48h.",
    bullets: ["Async", "Video breakdown", "48h turnaround"],
    delivery: "48 hours",
    imageBg: "#f8e3df",
    imageEmoji: "▷",
    tags: ["form", "async"],
  },

  // Longform
  {
    slug: "essay-ghostwrite",
    vendorSlug: "longform-co",
    title: "Ghostwritten essay",
    category: "Writing",
    price: 1500,
    priceType: "from",
    blurb: "1,500–3,000 words. Founder voice, your byline.",
    bullets: ["2 calls", "1 draft + 2 revisions", "Up to 3,000 words"],
    delivery: "2 weeks",
    imageBg: "#4a4a4a",
    imageEmoji: "❝",
    tags: ["essay", "ghost"],
  },
  {
    slug: "newsletter-monthly",
    vendorSlug: "longform-co",
    title: "Monthly newsletter — written",
    category: "Writing",
    price: 1800,
    priceType: "fixed",
    blurb: "4 newsletter issues per month. Your voice, our pen.",
    bullets: ["4 issues / mo", "Your voice", "Editorial calendar"],
    delivery: "Monthly",
    imageBg: "#e1e1e1",
    imageEmoji: "✉",
    tags: ["newsletter", "retainer"],
  },

  // Ground Floor
  {
    slug: "founder-coaching-session",
    vendorSlug: "ground-floor-advisory",
    title: "90-min founder session",
    category: "Consulting",
    price: 500,
    priceType: "fixed",
    blurb: "One deep session — pricing, GTM, or fundraising.",
    bullets: ["90 minutes", "Pre-call prep", "Written followup"],
    delivery: "Within 1 week",
    imageBg: "#0f5c4a",
    imageEmoji: "◆",
    tags: ["coaching", "session"],
  },
  {
    slug: "fundraising-prep-package",
    vendorSlug: "ground-floor-advisory",
    title: "Pre-seed fundraising prep",
    category: "Consulting",
    price: 4500,
    priceType: "from",
    blurb: "Deck, narrative, target list, and 4 prep sessions.",
    bullets: ["Deck review", "Pitch coaching", "Investor list"],
    delivery: "3 weeks",
    imageBg: "#cfe1d8",
    imageEmoji: "▣",
    tags: ["fundraising", "deck"],
  },
  {
    slug: "advisory-quarterly",
    vendorSlug: "ground-floor-advisory",
    title: "Quarterly advisory",
    category: "Consulting",
    price: 0,
    priceType: "inquiry",
    blurb: "Embedded advisor for one quarter. Equity or cash.",
    bullets: ["Weekly calls", "Slack access", "Quote on scope"],
    delivery: "Custom",
    imageBg: "#d6e5dd",
    imageEmoji: "✦",
    tags: ["advisor", "custom"],
  },

  // Studio Paloma
  {
    slug: "shoot-styling-day",
    vendorSlug: "studio-paloma",
    title: "Shoot styling — day rate",
    category: "Photo & Video",
    price: 1100,
    priceType: "fixed",
    blurb: "On-set styling for your photo or video shoot.",
    bullets: ["Full day", "Prop sourcing", "Set styling"],
    delivery: "Per booking",
    imageBg: "#9c6644",
    imageEmoji: "❀",
    tags: ["styling", "shoot"],
  },
  {
    slug: "interior-direction",
    vendorSlug: "studio-paloma",
    title: "Interior direction — small space",
    category: "Consulting",
    price: 2200,
    priceType: "from",
    blurb: "Direction package for a single room or small studio.",
    bullets: ["Site visit or virtual", "Mood + sourcing", "Final guide"],
    delivery: "3 weeks",
    imageBg: "#f0d8c5",
    imageEmoji: "◇",
    tags: ["interior"],
  },
  {
    slug: "custom-room-design",
    vendorSlug: "studio-paloma",
    title: "Custom full-room design",
    category: "Custom",
    price: 0,
    priceType: "inquiry",
    blurb: "Full-room design and procurement. Quote based on scope.",
    bullets: ["Full design", "Procurement", "Install support"],
    delivery: "Custom",
    imageBg: "#e8d3bd",
    imageEmoji: "❖",
    tags: ["custom", "interior"],
  },
];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getVendor(slug: string): Vendor | undefined {
  return vendors.find((v) => v.slug === slug);
}

export function productsByVendor(vendorSlug: string): Product[] {
  return products.filter((p) => p.vendorSlug === vendorSlug);
}

export function formatPrice(p: Product): string {
  if (p.priceType === "inquiry") return "Inquire";
  const formatted = `$${p.price.toLocaleString()}`;
  return p.priceType === "from" ? `From ${formatted}` : formatted;
}
